using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Diagnostics;
using SiteStock.Api.Common.Security;
using SiteStock.Api.Domain.Auditing;
using SiteStock.Api.Domain.Common;

namespace SiteStock.Api.Infrastructure.Persistence.Interceptors;

/// <summary>
/// Fills the audit columns and writes the append-only audit log, on every save, for every
/// entity. Doing it here rather than in services is the whole point: a developer adding a
/// feature in month six cannot forget it, because there is nothing to remember.
/// </summary>
public sealed class AuditSaveChangesInterceptor(
    ICurrentUser currentUser,
    IHttpContextAccessor httpContextAccessor,
    TimeProvider clock) : SaveChangesInterceptor
{
    /// <summary>Never written to the audit log — a password hash must not be recoverable from history.</summary>
    private static readonly HashSet<string> Redacted =
        new(StringComparer.OrdinalIgnoreCase) { "PasswordHash", "TokenHash" };

    /// <summary>
    /// Housekeeping the database does to itself. An update that touches nothing else is not
    /// a change anybody made — and left in, signing in five times a day buries the one row
    /// that says who altered a rate.
    /// </summary>
    private static readonly HashSet<string> NotAChange =
        new(StringComparer.OrdinalIgnoreCase)
        {
            "LastLoginAt", "FailedLoginCount", "LockedOutUntil",
        };

    /// <summary>
    /// Generated by the system rather than decided by a person. A notification per alert
    /// would be most of the log, and none of it would answer "who changed this".
    /// </summary>
    private static readonly HashSet<string> NotAudited =
        new(StringComparer.Ordinal) { "Notification" };

    public override InterceptionResult<int> SavingChanges(
        DbContextEventData eventData, InterceptionResult<int> result)
    {
        Apply(eventData.Context);
        return base.SavingChanges(eventData, result);
    }

    public override ValueTask<InterceptionResult<int>> SavingChangesAsync(
        DbContextEventData eventData, InterceptionResult<int> result, CancellationToken ct = default)
    {
        Apply(eventData.Context);
        return base.SavingChangesAsync(eventData, result, ct);
    }

    private void Apply(DbContext? context)
    {
        if (context is null) return;

        var now = clock.GetUtcNow();
        var userId = currentUser.IsAuthenticated ? currentUser.Id : (Guid?)null;
        var userName = currentUser.IsAuthenticated ? currentUser.FullName : "system";
        var correlationId = httpContextAccessor.HttpContext?.TraceIdentifier;

        var entries = new List<AuditLogEntry>();

        foreach (var entry in context.ChangeTracker.Entries<AuditableEntity>())
        {
            var audited = !NotAudited.Contains(entry.Metadata.ClrType.Name);

            switch (entry.State)
            {
                case EntityState.Added:
                    entry.Entity.CreatedAt = now;
                    entry.Entity.CreatedBy = userId;
                    if (audited)
                        entries.Add(Build(entry, AuditAction.Created, userId, userName, now, correlationId));
                    break;

                case EntityState.Modified:
                    entry.Entity.UpdatedAt = now;
                    entry.Entity.UpdatedBy = userId;

                    // Only when something a person would recognise actually moved.
                    if (audited && WorthLogging(entry))
                    {
                        entries.Add(Build(entry, AuditAction.Updated, userId, userName, now, correlationId));
                    }

                    break;

                case EntityState.Deleted:
                    if (audited)
                        entries.Add(Build(entry, AuditAction.Deleted, userId, userName, now, correlationId));
                    break;
            }
        }

        if (entries.Count > 0) context.Set<AuditLogEntry>().AddRange(entries);
    }

    /// <summary>
    /// The value as it should be stored for a human to read later.
    ///
    /// <para>An enum written as its underlying number turns "Issued → Sent" into "1 → 2",
    /// and a date-only value written as a timestamp invents a midnight that was never
    /// entered. Both are decided here, once, rather than guessed at when reading.</para>
    /// </summary>
    private static object? Readable(object? value) => value switch
    {
        null => null,
        Enum enumeration => enumeration.ToString(),
        DateOnly date => date.ToString("yyyy-MM-dd"),
        _ => value,
    };

    /// <summary>True when this update changed something other than login housekeeping.</summary>
    private static bool WorthLogging(EntityEntry<AuditableEntity> entry) =>
        entry.Properties.Any(p =>
            p.IsModified
            && !Equals(p.OriginalValue, p.CurrentValue)
            && !NotAChange.Contains(p.Metadata.Name));

    private static AuditLogEntry Build(
        EntityEntry<AuditableEntity> entry, AuditAction action,
        Guid? userId, string userName, DateTimeOffset now, string? correlationId)
    {
        var changes = new Dictionary<string, object?>();

        foreach (var property in entry.Properties)
        {
            var name = property.Metadata.Name;
            if (name is "CreatedAt" or "CreatedBy" or "UpdatedAt" or "UpdatedBy") continue;

            var isRedacted = Redacted.Contains(name);

            switch (action)
            {
                case AuditAction.Created when property.CurrentValue is not null:
                    changes[name] = isRedacted ? "***" : Readable(property.CurrentValue);
                    break;

                case AuditAction.Updated when property.IsModified &&
                                              !Equals(property.OriginalValue, property.CurrentValue):
                    changes[name] = isRedacted
                        ? new { from = "***", to = "***" }
                        : new { from = Readable(property.OriginalValue), to = Readable(property.CurrentValue) };
                    break;

                case AuditAction.Deleted when property.OriginalValue is not null:
                    changes[name] = isRedacted ? "***" : Readable(property.OriginalValue);
                    break;
            }
        }

        return new AuditLogEntry
        {
            EntityName = entry.Metadata.ClrType.Name,
            EntityId = entry.Entity.Id.ToString(),
            Action = action,
            Changes = JsonSerializer.Serialize(changes),
            ChangedBy = userId,
            ChangedByName = userName,
            ChangedAt = now,
            CorrelationId = correlationId,
        };
    }
}
