using SiteStock.Api.Domain.Common;
using SiteStock.Api.Domain.Organisation;

namespace SiteStock.Api.Domain.Contracts;

public enum WorkOrderStatus
{
    /// <summary>Work is on. Purchases can be raised against it.</summary>
    Active = 1,
    /// <summary>Paused by the client. Still visible, but should not attract new spend.</summary>
    OnHold = 2,
    /// <summary>Handed over. Kept for its history and its final cost.</summary>
    Completed = 3,
    Cancelled = 4,
}

/// <summary>
/// A contract won from a client — the work order they issued to us.
///
/// <para>This is the <b>revenue</b> side, and purchase orders are the cost side. A work order
/// says what a job is worth; the purchase orders raised against it say what it is costing.
/// Putting the two on one screen answers the question a contractor actually cares about:
/// am I still making money on this job.</para>
///
/// <para>The number is the client's, typed exactly as they issued it, not generated by us.
/// It is the reference everybody quotes, so a repeat is refused by the database.</para>
/// </summary>
public class WorkOrder : AuditableEntity
{
    /// <summary>What the client asked for, item by item. Empty until somebody types it in.</summary>
    public ICollection<WorkOrderLine> Lines { get; set; } = [];

    /// <summary>The client's own reference, e.g. <c>WO-2026-041</c>.</summary>
    public string Number { get; set; } = string.Empty;

    public string Title { get; set; } = string.Empty;

    /// <summary>Who awarded it — a builder, an EPC contractor, a utility.</summary>
    public string ClientName { get; set; } = string.Empty;

    public string? ClientReference { get; set; }

    /// <summary>
    /// The date printed on their order — "WO Date : 21.08.2025" on a Godrej sheet,
    /// "OrderNo/Date : 3200064035 / 08.05.2025" on a Kalpataru one. Not the day we typed it
    /// in, and not the day work starts: it is the date the contract will be quoted by.
    /// </summary>
    public DateOnly? OrderedOn { get; set; }

    /// <summary>Their GSTIN, as printed. What our invoice to them has to be raised against.</summary>
    public string? ClientGstin { get; set; }

    /// <summary>The client's registered address, off the head of their order.</summary>
    public string? ClientAddress { get; set; }

    /// <summary>
    /// Where our bill goes, which is routinely not the client's registered office — Godrej
    /// bill to the project store at Ambivali, not to Vikhroli.
    /// </summary>
    public string? BillingAddress { get; set; }

    /// <summary>Their "Kind Attn." — the person a query about this order goes to.</summary>
    public string? ClientContactName { get; set; }

    public string? ClientContactPhone { get; set; }

    /// <summary>
    /// The client's own name for the job — "Ambivali Project", "KALPATARU VIVANT". Our site
    /// is what we call it; this is what they will call it on the phone.
    /// </summary>
    public string? ProjectName { get; set; }

    /// <summary>
    /// Their credit terms in their own words: "97% in 30 days, 3% Retention money", or a
    /// paragraph about RA bills raised between the 1st and the 5th. It decides when we get
    /// paid, so it is kept verbatim rather than reduced to a number of days.
    /// </summary>
    public string? PaymentTerms { get; set; }

    /// <summary>Their amendment number, when the order has been revised. Blank on the original.</summary>
    public string? AmendmentVersion { get; set; }

    /// <summary>Where the work happens. A work order belongs to one site.</summary>
    public Guid SiteId { get; set; }
    public Site Site { get; set; } = null!;

    /// <summary>
    /// The total basic value — before any discount and before GST. This is the figure
    /// purchases are measured against, because GST is passed through and never was ours.
    /// </summary>
    public decimal ContractValue { get; set; }

    /// <summary>Any reduction the client applied to the basic value before tax.</summary>
    public decimal DiscountAmount { get; set; }

    /// <summary>
    /// Tax as their sheet splits it. Within Maharashtra it lands as CGST plus SGST; on an
    /// order from outside the state it is one IGST figure. Kept as three so the totals we
    /// show match the paper somebody is holding.
    /// </summary>
    public decimal CgstAmount { get; set; }
    public decimal SgstAmount { get; set; }
    public decimal IgstAmount { get; set; }

    public WorkOrderStatus Status { get; set; } = WorkOrderStatus.Active;

    public DateOnly? StartDate { get; set; }

    /// <summary>Contractual completion date, if there is one.</summary>
    public DateOnly? EndDate { get; set; }

    public string? ScopeSummary { get; set; }
    public string? Notes { get; set; }

    /// <summary>Basic value less discount — what the work is worth to us.</summary>
    public decimal NetValue => ContractValue - DiscountAmount;

    /// <summary>Their "Total WO Value": the net value with tax on top.</summary>
    public decimal TotalOrderValue => NetValue + CgstAmount + SgstAmount + IgstAmount;

    public bool IsOpen => Status is WorkOrderStatus.Active or WorkOrderStatus.OnHold;
}
